### ISSUE TITLE
Cannot define capabilities

### ISSUE THREAD

**Issue by amazpyel** [rodion-goritskov/test-analytics-ng#1]
I cannot define project capabilities, cells are not clickable. I have created attributes and components but cannot add capabilities. 

Steps to reproduce:
1. Create new project
2. Create attributes: simple, secure, integrated, fast
3. Create components: abc, bca, abs, dfg
4. Open Capabilities section
5. Click on ABC is simple cell

Expected result:
Possible to define capabilities

Actual result:
Cell is not clickable

**Comment by aaroncelt** [comment]
I have the same problem. Only the bottom right cell in the created matrix is clickable. All others are not clickable rendering this app useless until this is fixed. It's Impossible to define capabilities other than for the one and only cell that is clickable in the bottom right.

**Comment by rodion-goritskov** [comment]
@columbus13 @amazpyel @aaroncelt 
Hah, better late then never - fixed (:
https://github.com/rodion-goritskov/test-analytics-ng/pull/3

**Comment by dohertyaaronhmh** [comment]
:) forgot all about this, 
might revisit this again , 
Thanks for fixing

**Comment by amazpyel** [comment]
Well, I'm not even mad, that's amazing :)
